### PR TITLE
Tryout a white nav

### PR DESCRIPTION
**Pull request by frm**
This is more of a discussion PR but I think the white nav looks pretty great.
What do you guys think?

Feel free to reject it. Note that if we end up rejecting this, I'm using this
PR to fix the `color: white` lines and use `color: $color-white` instead.
:stuck_out_tongue:

### CODE REVIEW

**Comment by frm** [comment]
screen shot 2018-04-25 at 11 49 03
screen shot 2018-04-25 at 11 49 07

Screenshots for the lazy

**Comment by jfranciscosousa** [comment]
Add some shadow when it's over text?

**Comment by fribmendes** [comment]
screen shot 2018-04-26 at 11 13 36

**Comment by frm** [comment]
screen shot 2018-04-26 at 11 14 33

**Review by jfranciscosousa — APPROVED** [review]
Looks great, good job.

**Pull request merged**
