### PR TITLE
Add Terminal Style Component to landing page

### PR DESCRIPTION
**Pull request by luistorres**
- Adds a new Terminal component, based on this styles https://codepen.io/addyosmani/pen/avxmvN terminal style
- Updates landing page to be a terminal window

### CODE REVIEW

**Comment by luistorres** [comment]
screen shot 2018-05-02 at 19 52 22
What do you think?

**Comment by frm** [comment]
Me likes a lot! But it makes me think if we should decrease the title font size in this schema. Maybe just keep it bold?

**Comment by luistorres** [comment]
@fribmendes I'll check how it looks 👍

**Comment by luistorres** [comment]
screen shot 2018-05-03 at 22 11 35
@fribmendes is it better like this?

**Comment by luistorres** [comment]
screen shot 2018-05-03 at 22 22 25
Or maybe like this? So we can have an hierarchy in this situation?

**Comment by frm** [comment]
Last one 👍

**Comment by luistorres** [comment]
@fribmendes cool, it's already done. Proceed with the code review pls

**Review by jfranciscosousa — APPROVED** [review]
🇬🇭 🇦🇩 🇾🇪

**Pull request merged**
